### ISSUE TITLE
Seitenbaum statt Seitenwähler bei der Auswahl der Detailseite in der Listenansicht

### ISSUE THREAD

**Issue by ManuelaMe** [pdir/mobilede-bundle#1]
Beim Auswählen der Seite für die Detailansicht aus dem Inhaltselement Listenansicht herraus, bleibt im sich öffnenden Fenster der Seitenbaum angezeigt ohne möglichkeit auf den Seitenwähler zurück zu kommen.

Löschen des Caches hat nichts gebracht. Getestet mit Chrome und Firefox.

![image](https://user-images.githubusercontent.com/24274084/28776700-03ca79b6-75f8-11e7-873f-16085e86a5c7.png)

**Comment by MDevster** [comment]
fixed in [v.1.0.6](https://github.com/pdir/mobilede-bundle/releases/tag/v1.0.6)
