### ISSUE TITLE
Fehler-Meldung wenn API-Dienst nicht erreicht werden konnte

### ISSUE THREAD

**Issue by akroii** [pdir/mobilede-bundle#13]
Bisher ist es so, dass die Applikation bei einem Fehler des MobileDE Dienstes, die ganze Seite mit einem API-Error lahm legt. Es erscheint auf einer weißen Seite "MobileDe: API error". 
Kann man nicht stattdessen eine kleine Fehlermeldung innerhalb des Templates ablegen, welche greift, wenn der Dienst nicht erreichbar war?
Das wäre eine Verbesserung der Bedienfreundlichkeit der Nutzer.
Vlt. kann man auch einen Reload-Button hinterlegen, der beim drücken, den Dienst neu anspricht. In der Regel löste ein Reload das Problem, dass der Dienst nicht erreichbar war.

**Comment by akroii** [comment]
Bisher ist es so:
![bildschirmfoto 2018-06-07 um 09 49 07](https://user-images.githubusercontent.com/8830861/41095235-245a7a20-6a51-11e8-871e-756c5b6dbedb.png)

**Comment by MDevster** [comment]
fixed in 1.2.0
