### ISSUE TITLE
inventory-key bei Objekten verfügbar machen

### ISSUE THREAD

**Issue by MDevster** [pdir/mobilede-bundle#16]
ist es möglich die "internal number" bzw. "inventory-key“ auf der website anzeigen zulassen? es handelt sich dabei um die fahrzeugnummer. in der xml schnittstelle steht diese information nicht.

![34135793_1579969512132890_7398369969550917632_n](https://user-images.githubusercontent.com/10244240/41667360-0a40d0b0-74ad-11e8-90d7-d51149b66774.png)

**Comment by akroii** [comment]
Gibt es hierzu schon etwas neues?

**Comment by jommbee** [comment]
Würde mich auch interessieren. Diese Feature ist gerade in einem Projekt gefragt.

**Comment by seibtph** [comment]
@akroii @jommbee Bei unseren Tests wurde das Feld nicht übertragen. Hättet ihr evtl. API-Zugangsdaten, wo das Feld ausgefüllt ist und übergeben werden sollte? Falls das irgendwie möglich ist gern an support[AT]pdir.de wenden.

**Comment by jommbee** [comment]
Hi. Unser Projekt ist leider nicht mehr aktuell, kann hier also nicht weiterhelfen.

**Comment by akroii** [comment]
Ich habe auch kein Zugriff mehr auf das Projekt.

**Comment by MDevster** [comment]
Fixed in version 3.3.9.
