### ISSUE TITLE
Nach Update keine Daten mehr

### ISSUE THREAD

**Issue by PottiSeiler** [pdir/mobilede-bundle#17]
Hallo, 

nach dem Update wurde meine Version wieder in den DEMO Moduls gesetzt. Nach Klick auf Vollversion laden, wurde diese auch wieder aktiviert, allerdings liefert die Webseite keine mehr Daten aus.

Modus: Vollversion
IP: 2a00:1158:300::65e
Hostname: ananke.ispgateway.de
Domain: www.camping-kuhn.de

Woran kann das liegen? Brauchen Sie noch weitere Informationen von mir?

Danke und viele Grüße

**Comment by MDevster** [comment]
Welche Contao Version wird eingesetzt? Ab Contao 4.4 stellen wir die Sync Erweiterung nun über ein eigenes Repository bereit, sollten Sie hierfür noch keine Zugangsdaten besitzen, schreiben Sie bitte eine E-Mail an support AT pdir PUNKT de. In Contao 3 müssen weiterhin nach jedem Update unter Setup die Vollversion aktivieren.
