### ISSUE TITLE
Eingabefeld für Pseudopreis

### ISSUE THREAD

**Issue by akroii** [pdir/mobilede-bundle#21]
Ist es möglich bei einem Inserat Pseudopreise zu hinterlegen?
Also ein Preis welcher durchgestrichen ist.

Man kann ja ein eigenes Feld hinterlegen, welches man mit eigenen Werten hinterlegen kann.

**Comment by MDevster** [comment]
Für deinen Fall sollte es doch reichen das du dir einfach ein zusätzliches Eingabefeld in der lokalen Installation hinzufügst.

Mit dem "Paletten Manipulator"
https://docs.contao.org/dev/framework/dca/palettemanipulator/

Oder ähnlich wie hier https://pdir.de/news/formularfelder-in-contao-mit-einem-tooltip-ergaenzen.html
1 Ein neues Eingabefeld hinzufügen
2 Sprachdatei hinzufügen
3 Cache leeren

**Comment by MDevster** [comment]
@akroii Hat das bei dir funktioniert oder sollen wir das Feld in der nächsten Version mit aufnehmen?

**Comment by akroii** [comment]
@MDevster ich habe es noch nicht ausprobiert. mir würde die Dokumentation reichen. Es wäre trotzdem sehr sinnvoll so ein Feld zu implementieren. Pseudopreise sind ein wichtiger Marketing-Baustein :)

**Comment by MDevster** [comment]
Wird eingebaut :)

**Comment by MDevster** [comment]
added in version 3.2.0
