### ISSUE TITLE
Abruf von zwei Standort-Accounts über separate Listenmodule

### ISSUE THREAD

**Issue by Shoekrates** [pdir/mobilede-bundle#22]
Unser Kunde hat einen zweiten Standort aufgemacht, der einen separaten Login bei mobile.de hat. Ruft man die Standorte für sich alleine ab, funktioniert alles.
Allerdings lassen sich zwei Standorte über zwei separate Listenmodule nicht in der gleichen Contao-Installation abrufen – es werden immer nur die Fahrzeuge des zuletzt gespeicherten Listenmoduls angezeigt. Ich vermute, dass das mit dem Caching zusammenhängt? Kann man das irgendwie separieren?

Wie können wir die Darstellung der mobile.de-Inserate von zwei Standorten auf einer Website realisieren?
Die Kür bei der Problemlösung wäre natürlich die Kombination der Datensätze beider Standorte in einem Listenmodul, damit der Besucher der Website nicht auf separaten Unterseiten suchen muss.

**Comment by MDevster** [comment]
Die Anforderung wurde in Version 2.6.0 umgesetzt.
