### ISSUE TITLE
js-error and Filter is not working

### ISSUE THREAD

**Issue by hinzke** [pdir/mobilede-bundle#26]
## Bug description
```
Uncaught TypeError: b.container.isotope is not a function
    init https://domain.de/bundles/pdirmobilede/js/mobilede_module.min.js?v=e10a1486:1
    jQuery 8
    <anonymous> https://domain.de/bundles/pdirmobilede/js/mobilede_module.min.js?v=e10a1486:1
    <anonymous> https://domain.de/bundles/pdirmobilede/js/mobilede_module.min.js?v=e10a1486:1
```
## Steps to reproduce
loading page & and click on Filter-Button doesn't show the Filter-Options

## Environment
Contao 4.9.4
Browser Firefox

**Comment by akroii** [comment]
@hinzke you forgot to implement isotope: [https://isotope.metafizzy.co](https://isotope.metafizzy.co) 🙂

**Comment by hinzke** [comment]
Thanx, that's the solution

**Comment by akroii** [comment]
do not forget to close this issue 😉
