### ISSUE TITLE
Mobile.de API Fehler 405

### ISSUE THREAD

**Issue by ManuelaMe** [pdir/mobilede-bundle#3]
Nach dem Eingeben der API Benutzerdaten kommt eine Fehlermeldung von Mobile.de

> 405 (method not allowed)
This status code indicates that the endpoint either doesn’t support specified http verb (method) or the requested media type is not supported. Please check the value of the Accept header is correct as specified in the Media Types section.

![image](https://user-images.githubusercontent.com/24274084/29972242-c5f8552a-8f2b-11e7-882d-a0a1a701ccb2.png)

**Comment by MDevster** [comment]
Please use the new version of the module.
