### ISSUE TITLE
Installationsproblem

### ISSUE THREAD

**Issue by bkrmb** [pdir/mobilede-bundle#31]
Guten Tag, ich wollte die Demo testen und habe das Modul nach Ihrer Anleitung installiert. Bei Aufruf der Listenansicht erhalte ich allerdings eine Contao-Fehlermeldung.

In den Logs steht als letzter Eintrag folgendes:
`[2021-09-29 08:42:28] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT * FROM tl_vehicle WHERE account=0 ORDER BY *':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*' at line 1" at /home/www/optimist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT * FROM tl_vehicle WHERE account=0 ORDER BY *':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*' at line 1 at /home/www/optimist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*' at line 1 at /home/www/optimist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*' at line 1 at /home/www/optimist/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:137)"} []`

Wie bekomme ich das Modul zum laufen? Habe es jetzt auch schon mit und ohne die Demodaten probiert, habe auch noch einen Datensatz händisch angelegt. 
Grüße, Ben

**Comment by seibtph** [comment]
Hallo Ben,

entferne mal im Element der Listenansicht bei den Filter-Einstellungen im Feld **Sortieren nach** das *.  In der aktuellen Version ist das bereits behoben.

![sortieren-nach](https://user-images.githubusercontent.com/17127525/144406846-7827de1c-1165-4cac-8705-1cd7680f5f7a.png)
