### ISSUE TITLE
Could not find template "form_mate_upload"

### ISSUE THREAD

**Issue by mwell78** [pdir/mobilede-bundle#32]
Bei der Weiterleitung zur Fahrzeug-Detailseite wird das Template "form_mate_upload" nicht gefunden. Tatsächlich findet sich unter den Templates eines namens form_upload_mate. Wenn man das umbenennt funktioniert es...

```
Exception:
Could not find template "form_mate_upload"

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:158
  at Contao\TemplateLoader::getDefaultPath('form_mate_upload', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:114)
  at Contao\TemplateLoader::getPath('form_mate_upload', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:80)
  at Contao\Controller::getTemplate('form_mate_upload')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:324)
  at Contao\Widget->getTemplatePath('form_mate_upload', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:87)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:598)
...
```

## Environment
Contao 4.9.22
MATE-Theme 2.7.13
mobilede-sync-bundle-zip 1.2

**Comment by seibtph** [comment]
Du musst das Template nicht umbenennen, sondern nur das richtige Template bei dem Element auswählen. Dann sollte es funktionieren. form_upload_mate ist der richtige Name, ansonsten wird es im Select-Feld, wo man das Template auswählt, nicht angezeigt. Das ist nur in unseren Demodaten des MATE Theme falsch, das passen wir aber mit der nächsten Version an.
