### ISSUE TITLE
Mobile.de Contao - Contao list Cars

### ISSUE THREAD

**Issue by newfacemedia247** [pdir/mobilede-bundle#35]
Hi. We use the Mobile.de interface and integrate all vehicles via the list view at: https://hondaschmidt.de/fahrzeugangebote/suche

In the plugin itself there is no way to enter the number of "vehicles to be displayed".

Only 6 vehicles are currently displayed, although significantly more are available.
How can I show more vehicles?
![listcars](https://github.com/pdir/mobilede-bundle/assets/134620250/3fb44c8a-9d12-4c97-8393-46449bbee6f3)

Thanks for the reply, regards Sandro

**Comment by seibtph** [comment]
Hi Sandro,

please update the vehicle manager to the newest version. Than you can enter a maximum number of displayed vehicles.
