### ISSUE TITLE
Modulversion Contao Manager, Frontend und Backend stimmt nicht überein

### ISSUE THREAD

**Issue by ManuelaMe** [pdir/mobilede-bundle#4]
Contao Manager: 
![image](https://user-images.githubusercontent.com/24274084/31166559-7d3a8096-a8ef-11e7-980a-24bfd46e078b.png)
Frontend:
![image](https://user-images.githubusercontent.com/24274084/31166580-89562b64-a8ef-11e7-9293-42d5158298df.png)
Backend:
![image](https://user-images.githubusercontent.com/24274084/31166609-a49b9b8e-a8ef-11e7-93c1-f4fab4d69839.png)

Beim Update auf die Vollversion aus dem Backend tritt der Fehler 405 Method not allowed wieder auf.

**Comment by MDevster** [comment]
fixed in version 1.0.10
