### ISSUE TITLE
[Feature] Fahrzeugname im Alias

### ISSUE THREAD

**Issue by akroii** [pdir/mobilede-bundle#6]
Ist es möglich den Fahrzeugnamen im Alias anzuzeigen?
Bisher steht dort nur ein Integer.

Wenn dies nicht anders geht, könnte man ja die Nummer hinten anstellen.

**Comment by MDevster** [comment]
Grundsätzlich sollte das möglich sein, wir schauen mal wie wir das umsetzen könnten.

**Comment by MDevster** [comment]
fixed in version 2.0.0
