### ISSUE TITLE
Mehr Filtermethoden

### ISSUE THREAD

**Issue by akroii** [pdir/mobilede-bundle#8]
Sehr nützlich wäre es, wenn die Schnittstelle noch weitere Filter im Frontend hätte.
- Modell
- Fahrzeugart
- Kraftstoff
- Preis (vlt so eine art Begrenzungs-Slider)
- Kilometerstand (ebenfalls Begrenzungs-Slider)
- Leistung (ebenfalls Begrenzungs-Slider)

**Comment by MDevster** [comment]
added in 1.2.0
